const {magicStub} = require("./utilities");

module.exports = [
    // magicStub("%%!"),
    magicStub("%%bash"),
    magicStub("%%capture"),
    magicStub("%%debug"),
    magicStub("%%file"),
    magicStub("%%html"),
    magicStub("%%HTML"),
    magicStub("%%javascript"),
    magicStub("%%js"),
    magicStub("%%latex"),
    magicStub("%%markdown"),
    magicStub("%%perl"),
    magicStub("%%prun"),
    magicStub("%%pypy"),
    magicStub("%%python"),
    magicStub("%%python2"),
    magicStub("%%python3"),
    magicStub("%%ruby"),
    magicStub("%%script"),
    magicStub("%%sh"),
    magicStub("%%svg"),
    magicStub("%%SVG"),
    magicStub("%%sx"),
    magicStub("%%system"),
    magicStub("%%time"),
    magicStub("%%timeit"),
    magicStub("%%writefile"),
];
